services:
  db:
    image: postgres:18-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_sign_recognition:/var/lib/postgresql

  backend_road_signs:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_road_signs
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    
  frontend_road_signs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_road_signs
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend_road_signs

volumes:
  postgres_sign_recognition:
